project_id = "hrukgkkfkfvrhfkhfslk"

[functions.admin-list-users]
verify_jwt = true

[functions.admin-stats]
verify_jwt = true

[functions.admin-list-bookings]
verify_jwt = true

[functions.geocode-address]
verify_jwt = true

[functions.send-order-status-email]
verify_jwt = false
